# Generated by Django 5.2.5 on 2025-10-08 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_producto_gtin_movimientostock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='aplicado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='stock_antes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='stock_despues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto', 'numero_lote'], name='stock_lote_product_043368_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['fecha_venc'], name='stock_lote_fecha_v_819e68_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['lote', 'creado_en'], name='stock_movim_lote_id_a22471_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['aplicado_en'], name='stock_movim_aplicad_514f59_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['usuario'], name='stock_movim_usuario_a9aa9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='ck_lote_stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='ck_mov_cantidad_no_cero'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'AJUSTE'), models.Q(('tipo__in', ['INGRESO', 'EGRESO']), ('cantidad__gt', 0)), _connector='OR'), name='ck_mov_signo_por_tipo'),
        ),
    ]
